spring.application.name=tutor-time-tracker-api
server.port=8080

spring.datasource.url=${DB_URL:jdbc:mariadb://localhost:3307/tutortimetracker}
spring.datasource.username=${DB_USERNAME:tutortime}
spring.datasource.password=${DB_PASSWORD:tutortime}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.properties.hibernate.format_sql=true

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
